# # Étape 1 : Utiliser l'image Maven pour builder l'application
# FROM maven AS build

# # Répertoire de travail
# WORKDIR /app

# # Copier le fichier pom.xml et le répertoire src pour éviter de recopier tout à chaque fois
# COPY backend/pom.xml .
# COPY backend/src ./src

# # Lancer la commande de build Maven
# RUN mvn clean package -DskipTests

# Étape 1 : Utiliser une image Maven spécifique au JDK 17
FROM maven:3.9.6-eclipse-temurin-17 AS build

# Répertoire de travail
WORKDIR /app

# On copie le pom.xml d'abord pour mettre les dépendances en cache (optimisation Docker)
COPY backend/pom.xml .

# On force le téléchargement des dépendances proprement
RUN mvn dependency:go-offline -B

# Maintenant on copie les sources
COPY backend/src ./src

# On lance le build propre
RUN mvn clean package -DskipTests

# Étape 2 : Utiliser l'image JDK pour exécuter l'application
FROM eclipse-temurin:17-jdk-jammy

# Répertoire de travail
WORKDIR /app

# Copier le fichier JAR généré à partir de l'étape précédente
COPY --from=build /app/target/backend-0.1.0.jar app.jar

# Exposer le port sur lequel l'application Spring Boot va écouter
EXPOSE 8080

# Commande pour exécuter l'application
ENTRYPOINT ["java", "-jar", "app.jar"]
