INSERT INTO pizzas (name, price, image_url)
VALUES 
  ('Marguerite', 8.5, 'images/pizzas/margherite.webp'),
  ('Anchois', 8.5, 'images/pizzas/4saisons.webp'),
  ('Napolitaine', 8.5, 'images/pizzas/napoli.webp'),
  ('Jambonnière', 8.5, 'images/pizzas/jambonniere.webp'),
  ('Forestière', 8.5, 'images/pizzas/bufalina.webp'),
  ('Reine', 8.5, 'images/pizzas/reine.webp'),
  ('Oignons', 8.5, 'images/pizzas/lorenza.webp'),
  ('Knacki', 8.5, 'images/pizzas/pistachio.webp'),
  ('Chorizo', 9, 'images/pizzas/arrivederci.webp'),
  ('Thon et Câpres', 9, 'images/pizzas/traditional.webp'),
  ('Bolognaise', 9, 'images/pizzas/gasconne.webp'),
  ('Carbonara', 9, 'images/pizzas/estella.webp'),
  ('Chausson', 10, 'images/pizzas/napoli.webp'),
  ('Figatellu', 10, 'images/pizzas/proscuitto.webp'),
  ('Fruits de mer', 10, 'images/pizzas/salmone.webp'),
  ('Kebab', 10, 'images/pizzas/gasconne.webp'),
  ('Roquefort', 10, 'images/pizzas/mielina.webp'),
  ('3 Fromages', 10, 'images/pizzas/3fromages.webp'),
  ('Poivrons et Lardons', 10, 'images/pizzas/arrivederci.webp'),
  ('4 Saisons', 10, 'images/pizzas/4saisons.webp'),
  ('Pizza du chef', 10, 'images/pizzas/pistachio.webp'),
  ('Pizza de Sophie', 10, 'images/pizzas/estella.webp');
