INSERT INTO pizzas (name, base_price, image_url)
VALUES 
  ('Marguerite', 7.99, 'images/pizzas/olive.png'),
  ('Anchois', 9.49, 'images/pizzas/olive.png'),
  ('Napolitaine', 10.99, 'images/pizzas/olive.png'),
  ('Jambonnière', 8.99, 'images/pizzas/olive.png'),
  ('Forestière', 9.29, 'images/pizzas/olive.png'),
  ('Reine', 9.29, 'images/pizzas/olive.png'),
  ('Oignons', 9.29, 'images/pizzas/olive.png'),
  ('Knacky', 9.29, 'images/pizzas/olive.png'),
  ('Chorizo', 9.29, 'images/pizzas/olive.png'),
  ('Thon et Câpres', 9.29, 'images/pizzas/olive.png'),
  ('Bolognaise', 9.29, 'images/pizzas/olive.png'),
  ('Carbonara', 9.29, 'images/pizzas/olive.png'),
  ('Chausson', 9.29, 'images/pizzas/olive.png'),
  ('Figatellu', 9.29, 'images/pizzas/olive.png'),
  ('Fruits de mer', 9.29, 'images/pizzas/olive.png'),
  ('Kebab', 9.29, 'images/pizzas/olive.png'),
  ('Roquefort', 9.29, 'images/pizzas/olive.png'),
  ('3 Fromages', 9.29, 'images/pizzas/olive.png'),
  ('Poivrons et Lardons', 9.29, 'images/pizzas/olive.png'),
  ('4 Saisons', 9.29, 'images/pizzas/olive.png'),
  ('Pizza du chef', 9.29, 'images/pizzas/olive.png'),
  ('Pizza de Sophie', 9.29, 'images/pizzas/olive.png');
