INSERT INTO pizzas (name, price, image_url)
VALUES 
  ('Marguerite', 8.5, 'images/pizzas/margherite.webp'),
  ('Anchois', 8.5, 'images/pizzas/anchois.jpg'),
  ('Napolitaine', 8.5, 'images/pizzas/olive.png'),
  ('Jambonnière', 8.5, 'images/pizzas/olive.png'),
  ('Forestière', 8.5, 'images/pizzas/olive.png'),
  ('Reine', 8.5, 'images/pizzas/olive.png'),
  ('Oignons', 8.5, 'images/pizzas/olive.png'),
  ('Knacky', 8.5, 'images/pizzas/olive.png'),
  ('Chorizo', 9, 'images/pizzas/olive.png'),
  ('Thon et Câpres', 9, 'images/pizzas/olive.png'),
  ('Bolognaise', 9, 'images/pizzas/olive.png'),
  ('Carbonara', 9, 'images/pizzas/olive.png'),
  ('Chausson', 10, 'images/pizzas/olive.png'),
  ('Figatellu', 10, 'images/pizzas/olive.png'),
  ('Fruits de mer', 10, 'images/pizzas/olive.png'),
  ('Kebab', 10, 'images/pizzas/olive.png'),
  ('Roquefort', 10, 'images/pizzas/olive.png'),
  ('3 Fromages', 10, 'images/pizzas/olive.png'),
  ('Poivrons et Lardons', 10, 'images/pizzas/olive.png'),
  ('4 Saisons', 10, 'images/pizzas/olive.png'),
  ('Pizza du chef', 10, 'images/pizzas/olive.png'),
  ('Pizza de Sophie', 10, 'images/pizzas/olive.png');
