INSERT INTO ingredients (name, available_as_supplement, supplement_price, image_url)
VALUES 
  ('Gruyère', TRUE, 1.50, 'images/ingredients/cheese.jpg'),
  ('Mozzarella', TRUE, 1.50, 'images/ingredients/mozarella.jpg'),
  ('Olives', TRUE, 1.50, 'images/ingredients/olives.jpg'),
  ('Anchois', TRUE, 1.50, 'images/ingredients/anchois.jpg'),
  ('Jambon', TRUE, 1.50, 'images/ingredients/jambon.jpg'),
  ('Champignons', TRUE, 1.50, 'images/ingredients/champignons.jpg'),
  ('Oignons', TRUE, 1.50, 'images/ingredients/oignons.jpg'),
  ('Knacky', TRUE, 1.50, 'images/ingredients/knacky.jpg'),
  ('Chorizo', TRUE, 1.50, 'images/ingredients/chorizo.jpg'),
  ('Thon', TRUE, 1.50, 'images/ingredients/thon.jpg'),
  ('Câpres', TRUE, 1.50, 'images/ingredients/capres.jpg'),
  ('Bolognaise', TRUE, 1.50, 'images/ingredients/bolognaise.jpg'),
  ('Lardons', TRUE, 1.50, 'images/ingredients/lardons.jpg'),
  ('Oeuf', TRUE, 1.50, 'images/ingredients/oeuf.jpg'),
  ('Figatellu', TRUE, 1.50, 'images/ingredients/figatellu.jpg'),
  ('Fruits de mer', TRUE, 1.50, 'images/ingredients/fruits_de_mer.jpg'),
  ('Kebab', TRUE, 1.50, 'images/ingredients/kebab.jpg'),
  ('Roquefort', TRUE, 1.50, 'images/ingredients/roquefort.jpg'),
  ('Chèvre', TRUE, 1.50, 'images/ingredients/chevre.jpg'),
  ('Poivrons', TRUE, 1.50, 'images/ingredients/poivrons.jpg'),
  ('Coeurs d''artichaut', TRUE, 1.50, 'images/ingredients/artichaut.jpg'),
  ('Aubergine', TRUE, 1.50, 'images/ingredients/aubergine.jpg'),
  ('Miel', TRUE, 1.50, 'images/ingredients/miel.jpg'),
  ('Pignons', TRUE, 1.50, 'images/ingredients/pignons.jpg');
