INSERT INTO ingredients (name, available_as_supplement, supplement_price, image_url)
VALUES 
  ('Gruyère', TRUE, 7.99, 'images/pizzas/olive.png'),
  ('Mozzarella', TRUE, 9.49, 'images/pizzas/olive.png'),
  ('Olives', TRUE, 10.99, 'images/pizzas/olive.png'),
  ('Anchois', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Jambon', TRUE, 9.29, 'images/pizzas/olive.png'),
  ('Champignons', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Oignons', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Knacky', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Chorizo', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Thon', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Câpres', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Bolognaise', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Lardons', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Oeuf', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Figatellu', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Fruits de mer', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Kebab', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Roquefort', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Chèvre', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Poivrons', TRUE, 8.99, 'images/pizzas/olive.png'),
  ("Coeurs d'artichaut", TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Aubergine', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Miel', TRUE, 8.99, 'images/pizzas/olive.png'),
  ('Pignons', TRUE, 8.99, 'images/pizzas/olive.png');
